services:
  redis:
    image: valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    cap_add: [SETGID, SETUID, DAC_OVERRIDE]
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  searxng:
    image: searxng/searxng:latest
    volumes:
      - /searxng:/etc/searxng:rw,z
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL:-http://localhost:8080/}
      SEARXNG_SECRET_KEY: ${SEARXNG_SECRET_KEY}
      UWSGI_WORKERS: 4
      UWSGI_THREADS: 4
    cap_add: [CHOWN, SETGID, SETUID]
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - /frontend/agentic-seek-front/src:/app/src:rw,z
      - /screenshots:/app/screenshots
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: http://host.docker.internal:${BACKEND_PORT:-7777}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - /backend:/app
      - /workspace:/opt/workspace
    command: python3 api.py
    environment:
      SEARXNG_URL: ${SEARXNG_BASE_URL:-http://searxng:8080}
      REDIS_URL: ${REDIS_BASE_URL:-redis://redis:6379/0}
      WORK_DIR: /opt/workspace
      BACKEND_PORT: ${BACKEND_PORT:-7777}
      DOCKER_INTERNAL_URL: http://host.docker.internal
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      DSK_DEEPSEEK_API_KEY: ${DSK_DEEPSEEK_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
